//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordMaster {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Words {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Words() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordMaster.Words", typeof(Words).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to скучный.
        /// </summary>
        internal static string aburrido {
            get {
                return ResourceManager.GetString("aburrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to весёлый.
        /// </summary>
        internal static string alegre {
            get {
                return ResourceManager.GetString("alegre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дешёвый.
        /// </summary>
        internal static string barato {
            get {
                return ResourceManager.GetString("barato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хороший.
        /// </summary>
        internal static string bueno {
            get {
                return ResourceManager.GetString("bueno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дорогой.
        /// </summary>
        internal static string caro {
            get {
                return ResourceManager.GetString("caro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to трудный.
        /// </summary>
        internal static string difícil {
            get {
                return ResourceManager.GetString("difícil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to забавный.
        /// </summary>
        internal static string divertido {
            get {
                return ResourceManager.GetString("divertido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лёгкий.
        /// </summary>
        internal static string fácil {
            get {
                return ResourceManager.GetString("fácil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to уродливый.
        /// </summary>
        internal static string feo {
            get {
                return ResourceManager.GetString("feo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to большой.
        /// </summary>
        internal static string grande {
            get {
                return ResourceManager.GetString("grande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to красивый.
        /// </summary>
        internal static string hermoso {
            get {
                return ResourceManager.GetString("hermoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to умный.
        /// </summary>
        internal static string inteligente {
            get {
                return ResourceManager.GetString("inteligente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to молодой.
        /// </summary>
        internal static string joven {
            get {
                return ResourceManager.GetString("joven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to плохой.
        /// </summary>
        internal static string malo {
            get {
                return ResourceManager.GetString("malo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to новый.
        /// </summary>
        internal static string nuevo {
            get {
                return ResourceManager.GetString("nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to маленький.
        /// </summary>
        internal static string pequeño {
            get {
                return ResourceManager.GetString("pequeño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бедный.
        /// </summary>
        internal static string pobre {
            get {
                return ResourceManager.GetString("pobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to богатый.
        /// </summary>
        internal static string rico {
            get {
                return ResourceManager.GetString("rico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to глупый.
        /// </summary>
        internal static string tonto {
            get {
                return ResourceManager.GetString("tonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грустный.
        /// </summary>
        internal static string triste {
            get {
                return ResourceManager.GetString("triste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to старый.
        /// </summary>
        internal static string viejo {
            get {
                return ResourceManager.GetString("viejo", resourceCulture);
            }
        }
    }
}
